version: "3"
services:
  db:
    image: "postgres:15"
    container_name: "gyst_postgres"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
      - my_dbbackup:/backups
volumes:
  my_dbdata:
  my_dbbackup: